### PR TITLE
fix: dont patch `getuid` and `getgid` on process anymore #809

### LINKED ISSUE #809: Side effect when mocking `process.getuid()` under Windows
Recently I have found that when I imported `memfs/lib/process.js` and used `gulp` to copy a directory with a subdirectory, I got an error `Error: EPERM: operation not permitted, futime`.

```
dest
test
│   index.js
└───sub
    │   index.js
```

Here is the snippet to show how to reproduce the problem:

```js
// test/index.js
const path = require('path');
const gulp = require('gulp');

// require('memfs/lib/process.js');
process.getuid = process.getuid || (() => 0);
gulp.src(['**/*']).pipe(gulp.dest(path.resolve(__dirname, '../dest')))
```

It seems that it is a mocked `uid` resulting in side effects when trying to `futime`.

The temporary workaround is to revert it within the current process:

```js
require('memfs');
process.platform === 'win32' && delete process.getuid;
```

### PR DESCRIPTION
**Pull request by aleen42**
Resolves #809

### CODE REVIEW

File: src/node.ts [hunk 1]
```diff
@@ -17,7 +17,6 @@ export class Node extends EventEmitter {
   ino: number;
 
   // User ID and group ID.
-  uid: number = process.getuid();
```
Comment (G-Rath) [inline src/node.ts:20]: This shouldn't be removed as it's public + used by the rest of this class.

I think let's abstract the falling back behaviour into a small helper function within this file and then we can call that everywhere, e.g.

```
const getuid = (): number => process.getuid?.() ?? 0

export class Node extends EventEmitter {
  // ...
  uid: number = getuid();
}
```

**Review by G-Rath — CHANGES_REQUESTED** [review]
Looks good, just need to restore the `uid` property.

Would you be open to also replacing `getgid` in this PR too, since that change is pretty much the same thing?

File: src/__tests__/process.test.ts [hunk 2]
```diff
@@ -7,8 +7,8 @@ describe('process', () => {
       expect(typeof _process).toBe('object');
     });
     it('.getuid() and .getgid()', () => {
-      expect(typeof proc.getuid()).toBe('number');
-      expect(typeof proc.getgid()).toBe('number');
+      expect(typeof proc.getuid?.() ?? 0).toBe('number');
+      expect(typeof proc.getgid?.() ?? 0).toBe('number');
     });
```
Comment (G-Rath) [inline src/__tests__/process.test.ts:12]: nit: we should remove this test entirely as it's not really covering anything useful now

**Review by G-Rath — APPROVED** [review]
