### PR TITLE
fix: `mkdir` return value

### LINKED ISSUE #546: Typing mismatch between fs.mkdir and memfs.mkdir
Firstly and most importantly, huge thanks for this package, it's awesome.

I tried to drop in the output from `createFsFromVolume()` instead of the native `fs` and I hit a snag. There's a minor typing mismatch.

```
Conversion of type 'IFs' to type 'FS' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  The types returned by 'promises.mkdir(...)' are incompatible between these types.
    Type 'Promise<void>' is not comparable to type 'Promise<string>'.
      Type 'void' is not comparable to type 'string'.ts(2352)
```

Looking into this a little, the node [fs.mkdir](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback) and [fs.promises.mkdir](https://nodejs.org/api/fs.html#fs_fspromises_mkdir_path_options) optionally return the path to the first directory created when the `recursive: true` option is set. While `memfs.mkdir` always returns `void`.

### PR DESCRIPTION
**Pull request by toyobayashi**
https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fsmkdirpath-options-callback

> The callback is given a possible exception and, if recursive is true, the first directory path created, (err[, path]). path can still be undefined when recursive is true, if no directory was created.

https://nodejs.org/dist/latest-v18.x/docs/api/fs.html#fsmkdirsyncpath-options

> Synchronously creates a directory. Returns undefined, or if recursive is true, the first directory path created.

Resolves #546

### CODE REVIEW

**Comment by toyobayashi** [comment]
not sure why Jest runs timeout on macOS CI

**Comment by toyobayashi** [comment]
Perhaps this PR can fix #546

File: src/volume.ts [hunk 1]
```diff
@@ -1920,8 +1922,11 @@ export class Volume {
    * @param modeNum
    */
   private mkdirpBase(filename: string, modeNum: number) {
-    const steps = filenameToSteps(filename);
+    const fullPath = resolve(filename);
+    const fullPathSansSlash = fullPath.substr(1);
```
Comment (G-Rath) [inline src/volume.ts:1926]: `substr` is deprecated - can we replace this with `substring`?

Comment (toyobayashi) [reply src/volume.ts]: Done.

**Review by G-Rath — APPROVED** [review]
